version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nfs-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - nfsnet

  api:
    build:
      context: ./src
      dockerfile: ./Presentation/Dockerfile
    container_name: nfs-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=NfsDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"
    networks:
      - nfsnet

networks:
  nfsnet:

volumes:
  sql_data:
